# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0eddfc0516fdefcdebfe2f02794f98507314eec1d3be31bd238867ec0583c80535af143835c18a4912b528e68739cb8105a60045b2fcacf52fd9a3211e3c4ff

test:
  secret_key_base: d07c3b0db9122cf9370e1d347b9517083ea12a589dfff214368e581431756208f5ced15985f9062ada67b57167f2126c5aa7287576791d899f80f811884036bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
